### ISSUE TITLE
'f' is not defined 

### ISSUE THREAD

**Issue by sibu86** [wgpsec/CS-Avoid-killing#1]
![WhatsApp Image 2021-05-05 at 7 47 41 PM](https://user-images.githubusercontent.com/83626186/117174837-baac0200-ae00-11eb-9bd3-37161ee5c433.jpeg)

**Comment by sibu86** [comment]
Same issue when run in Admin console and linux with python3

**Comment by Gality369** [comment]
Usage：python3 PSconfusion.py RawCSpayload.ps1 ConfusionPayload.ps1
you miss the arguments

**Comment by sibu86** [comment]
Got it. THanks!
